### ISSUE TITLE
Why PPOs don't have success rates

### ISSUE THREAD

**Issue by jkasdkjnasjkd** [zeyang23/panda_robot_task#2]
Why PPOs don't have success rates

**Comment by zeyang23** [comment]
Hello~ @jkasdkjnasjkd 
For sparse reward environments, it may take millions of samples for PPO to have a success rate larger than zero. It is also possible that PPO just cannot perform well on an enviornment. Try tuning the parameters of PPO or switch to other algorithms such as SAC.
